# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always


- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/newuser/zz_data/temp_delete/ansible
    state: directory
    owner: newuser
    group: newuser
    mode: '0755'

- name: Example clone of a single branch
  ansible.builtin.git:
    repo: https://github.com/parvezk-code/Library.git
    dest: /home/newuser/zz_data/temp_delete/ansible/Library
    single_branch: yes
    version: master
  ignore_errors: true

- name: Change directory permissions
  ansible.builtin.file:
    path: /home/newuser/zz_data/temp_delete/ansible/Library
    state: directory
    recurse: yes
    owner: newuser
    group: newuser
