#!/bin/sh
exec tail -n +3 $0

# Path to the Ubuntu ISO file
ISO_PATH="/home/newuser/zz_data/ubuntu-22.04.3-desktop-amd64.iso"

# GRUB device and partition where the ISO file is located.
# Format: (hdX,Y)
# X is the disk number (starting at 0)
# Y is the partition number (starting at 1)
PARTITION="(hd1,6)"

# Variable used in the GRUB menuentry for referencing the ISO file path.
# Backslash before $ delays expansion until boot time.
ISO_VAR="\$isofile"

# Mount the ISO and check where vmlinuz(kernel image) is located.
KERNEL_PATH="/casper/vmlinuz"

# Mount the ISO and check where initrd.img(RAM disk image) is located.
INITRD_PATH="/casper/initrd"

# === GRUB menuentry output ===
cat << EOF
menuentry "Try or Install Ubuntu 22.04 ISO" {
    set isofile="${ISO_PATH}"
    loopback loop ${PARTITION}\${ISO_VAR}
    linux (loop)${KERNEL_PATH} file=/cdrom/preseed/ubuntu.seed boot=casper iso-scan/filename=\${ISO_VAR} quiet splash ---
    initrd (loop)${INITRD_PATH}
}
EOF


# Make the file executable          :       sudo chmod +x /etc/grub.d/47_install_ubuntu

# Update GRUB config                :       sudo update-grub