- name: KDE Desktop | install package |
  tags: KDE
  package:
    name:
      - sddm
      - xserver-xorg
      - plasma-desktop
      - plasma-workspace
      - plasma-nm
      - kde-spectacle
      - udisks2
      - upower
      - partitionmanager
      - konsole

#  plasma-desktop  <   kde-plasma-desktop  <   kde-standard    <   kde-full
#  task-kde-desktop is Debian's selection of applications for a KDE desktop
