# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  - import_tasks: handlers/cloneGitRepo.yml
    when:
      - cloneGitRepo is defined
      - cloneGitRepo == true
