- name: software | kdenlive | copy launcher
  tags: apps,appimage,software,kdenlive
  copy:
    src: users/jay/kdenlive.desktop
    dest: /home/jay/.local/share/applications/kdenlive.desktop
    owner: jay
    group: jay
    mode: 0700

- name: software | kdenlive | install package
  get_url:
    url: https://download.kde.org/stable/kdenlive/20.08/linux/kdenlive-20.08.2-x86_64.appimage
    dest: /home/jay/bin/kdenlive.app
    mode: '0700'
    owner: jay
    group: jay


----------------------------------------  kdenlive.desktop  ------------------------------------------------

# KDE Config File
[Desktop Entry]
Name=Kdenlive
GenericName=Video Editor
Comment=Nonlinear video editor by KDE
Type=Application
Exec=/home/jay/bin/kdenlive.app %F
Icon=kdenlive
X-DocPath=kdenlive/index.html
X-DocPath[cs]=http://cs.wikibooks.org/wiki/Kdenlive
Terminal=false
MimeType=application/x-kdenlive;
Categories=Qt;KDE;AudioVideo;AudioVideoEditing;
Keywords=video;audio;firewire;video4linux;suite;editing;kde;mlt;
X-DBUS-ServiceName=org.kde.kdenlive

----------------------------------------------------------------------------------------





