- name: software | authy | install package
  tags: packages,authy,snap,workstation-packages
  snap:
    name:  authy
    channel: latest/edge
    state: present
  when:
    - ansible_distribution != "Archlinux"
    - authy is defined
    - authy == true

# set up snap support
# Note: Not available in Arch currently as of 2020-09-15
- name: system setup | tweaks | install snapd
  package:
    name: snapd
    state: latest
  when: ansible_distribution != "Archlinux"

# Ensure core snap is installed
- name: system setup | tweaks | install/update core snap
  tags: packages,snap,todoist,workstation-packages
  snap:
    name:  core
    state: present
  when: ansible_distribution != "Archlinux"
