
- name: Check repo directory exists
  stat:
    path: '{{ gitRepoDir }}'
  register: repoDirExists

- debug: var=repoDirExists.stat.exists

- debug: var=repoDirExists.stat.isdir

- name: Example clone of a single branch
  ansible.builtin.git:
    repo: '{{ gitRepoUrl }}'
    dest: '{{ gitRepoDir }}'
    single_branch: yes
    version: master
    force: false
  ignore_errors: true
  when: not (repoDirExists.stat.exists and repoDirExists.stat.isdir)

- name: Change directory permissions
  ansible.builtin.file:
    path: '{{ gitRepoDir }}'
    state: directory
    recurse: yes
    owner: '{{ dataDirOwner }}'
    group: '{{ dataDirGroup }}'
  when: not (repoDirExists.stat.exists and repoDirExists.stat.isdir)
